language: php
sudo: false
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

cache:
  directories:
    - build/.composer-cache

before_install:
  - export COMPOSER_CACHE_DIR="$(pwd)/build/.composer-cache"
  - export XDEBUG="/home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini"
  - is_hhvm () { [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; }
  - is_hhvm || mv -v "$XDEBUG" "$XDEBUG.disabled"

install:
  - mkdir -p build/php_codesniffer build/php-cs-fixer build/ocular
  - is_hhvm || composer require --no-suggest --no-progress -n -a -d build/php-cs-fixer "friendsofphp/php-cs-fixer:^2.5"
  - composer require --no-suggest --no-progress -n -a -d build/php_codesniffer "squizlabs/php_codesniffer:^3.0"
  - composer require --no-suggest --no-progress -n -a -d build/ocular "scrutinizer/ocular:^1.4"
  - composer update --no-suggest --no-progress -na

script:
  - build/php_codesniffer/vendor/bin/phpcs -p --standard=PSR2 src tests
  - is_hhvm || build/php-cs-fixer/vendor/bin/php-cs-fixer fix -v --dry-run --allow-risky=yes --using-cache=no
  - if is_hhvm; then echo "xdebug.enable = On" >> /etc/hhvm/php.ini; else mv -v "$XDEBUG.disabled" "$XDEBUG"; fi
  - vendor/bin/phpunit --coverage-clover=build/coverage.clover --coverage-text

after_script:
  - is_hhvm || build/ocular/vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage.clover
